version: "3.7"
services:

  db:
    image: postgres:16
    container_name: db_shop
    env_file:
      - .env_non_dev

  redis:
    image: redis:7
    container_name: redis_shop

  app:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: app_shop
    command: ["/shop_app/docker_scripts/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - redis
      - db

  celery:
    build:
      context: .
    env_file:
      - .env_non_dev
    container_name: celery_shop
    command: celery --app=src.tasks.email_task:celery worker -l INFO
    depends_on:
      - redis

  flower:
    container_name: flower_shop
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis